import { useEffect, useState } from 'react'
import axios from 'axios'

const BASE='http://localhost:8000'
const yearLabel=y=>({1:'1st Year',2:'2nd Year',3:'3rd Year',4:'4th Year'}[y])

export default function AcademicSubjects(){
 const [groups,setGroups]=useState([]); const [groupId,setGroupId]=useState(''); const [subjects,setSubjects]=useState([])
 const [name,setName]=useState(''); const [type,setType]=useState('theory'); const [periods,setPeriods]=useState(3); const [message,setMessage]=useState(''); const [error,setError]=useState('')
 async function load(){try{const [g,s]=await Promise.all([axios.get(`${BASE}/academic-structure`),axios.get(`${BASE}/academic-subjects`)]);setGroups(g.data?.groups || []);setSubjects(Array.isArray(s.data) ? s.data : (s.data?.subjects || []))}catch(err){console.error(err);setError('Could not load academic data.')}}
 useEffect(()=>{load()},[])
 const group=groups.find(g=>String(g.group_id)===String(groupId)); const groupSubjects=subjects.filter(s=>s.group_id===Number(groupId))
 async function submit(e){e.preventDefault();setMessage('');setError('');if(!groupId||!name.trim()){setError('Select a department/year and enter a subject name.');return}try{const r=await axios.post(`${BASE}/academic-subjects`,{group_id:Number(groupId),subject_name:name.trim(),subject_type:type,periods_per_week:Number(periods)});setMessage(`${r.data.subject_name} added to all divisions: ${r.data.assigned_to_divisions.join(', ')}`);setName('');await load()}catch(err){setError(err.response?.data?.detail||'Could not save subject.')}}
 return <div style={page}><section style={hero}><div style={eyebrow}>STEP 2 · SUBJECTS</div><h1 style={title}>Subjects</h1><p style={sub}>Select one department and year. A subject is created once and automatically belongs to every division of that academic group.</p></section>
 <section style={card}><h2 style={h2}>Select academic group</h2><select value={groupId} onChange={e=>setGroupId(e.target.value)} style={input}><option value="">Select department and year</option>{groups.map(g=><option key={g.group_id} value={g.group_id}>{g.department} · {yearLabel(g.year_of_study)} · Divisions {g.divisions.map(d=>d.division_name).join(', ')}</option>)}</select>{group&&<div style={context}><b>{group.department} · {yearLabel(group.year_of_study)}</b><span>Divisions: {group.divisions.map(d=>d.division_name).join(', ')}</span></div>}
 <form onSubmit={submit} style={{marginTop:20}}><div style={grid3}><Field label="Subject name"><input value={name} onChange={e=>setName(e.target.value)} placeholder="DBMS" style={input}/></Field><Field label="Type"><select value={type} onChange={e=>setType(e.target.value)} style={input}><option value="theory">Theory</option><option value="lab">Lab</option></select></Field><Field label="Periods / week"><input type="number" min="1" max="30" value={periods} onChange={e=>setPeriods(e.target.value)} style={input}/></Field></div><button style={button}>Add Subject to All Divisions</button></form>{message&&<div style={success}>{message}</div>}{error&&<div style={errorBox}>{error}</div>}</section>
 <section style={card}><h2 style={h2}>Subjects for this academic group</h2>{!groupId?<p style={muted}>Select a department/year above.</p>:groupSubjects.length===0?<p style={muted}>No subjects added yet.</p>:<div style={table}><div style={thead}><span>Subject</span><span>Type</span><span>Periods</span><span>Scope</span></div>{groupSubjects.map(s=><div key={s.definition_id} style={tr}><b>{s.subject_name}</b><span style={badge}>{s.subject_type}</span><span>{s.periods_per_week}</span><span>{group?.divisions.map(d=>d.division_name).join(', ')}</span></div>)}</div>}</section></div>
}
function Field({label,children}){return <label style={{display:'grid',gap:7}}><span style={labelStyle}>{label}</span>{children}</label>}
const page={padding:'34px 38px',maxWidth:1100,margin:'0 auto'};const hero={padding:'28px 30px',borderRadius:18,background:'linear-gradient(135deg,#eef5ff,#f7f4ff)',border:'1px solid #dbe5f5',marginBottom:20};const eyebrow={fontSize:11,fontWeight:800,letterSpacing:'.12em',color:'#4f46e5'};const title={fontSize:32,margin:'8px 0 6px',color:'#172554'};const sub={margin:0,color:'#64748b',fontSize:15,lineHeight:1.6};const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:16,padding:26,marginBottom:20,boxShadow:'0 5px 20px rgba(15,23,42,.04)'};const h2={fontSize:19,color:'#172554',margin:'0 0 16px'};const input={width:'100%',boxSizing:'border-box',padding:'11px 12px',border:'1px solid #cbd5e1',borderRadius:9,fontSize:14,background:'#fff'};const grid3={display:'grid',gridTemplateColumns:'2fr 1fr 1fr',gap:14};const button={marginTop:18,padding:'12px 20px',border:0,borderRadius:10,background:'linear-gradient(90deg,#2563eb,#6d28d9)',color:'#fff',fontWeight:800,cursor:'pointer'};const labelStyle={fontSize:11,fontWeight:800,letterSpacing:'.08em',color:'#64748b'};const muted={color:'#64748b',fontSize:13};const context={marginTop:14,padding:13,borderRadius:10,background:'#eff6ff',color:'#1e3a8a',display:'flex',justifyContent:'space-between'};const success={marginTop:14,padding:12,borderRadius:9,background:'#ecfdf5',color:'#047857'};const errorBox={marginTop:14,padding:12,borderRadius:9,background:'#fef2f2',color:'#b91c1c'};const table={border:'1px solid #e2e8f0',borderRadius:10,overflow:'hidden'};const thead={display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1.5fr',padding:12,background:'#f8fafc',fontSize:11,fontWeight:800,color:'#64748b',textTransform:'uppercase'};const tr={display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1.5fr',padding:13,borderTop:'1px solid #e2e8f0',alignItems:'center'};const badge={fontSize:11,fontWeight:700,textTransform:'capitalize'}
