import { useEffect, useState } from 'react'
import axios from 'axios'

const BASE='http://localhost:8000'
const yearLabel=y=>({1:'1st Year',2:'2nd Year',3:'3rd Year',4:'4th Year'}[y])

export default function FacultyAssignments(){
 const [teachers,setTeachers]=useState([]),[groups,setGroups]=useState([]),[assignments,setAssignments]=useState([])
 const [name,setName]=useState(''),[max,setMax]=useState(6),[groupId,setGroupId]=useState(''),[teacherId,setTeacherId]=useState(''),[definitionId,setDefinitionId]=useState(''),[divisionIds,setDivisionIds]=useState([]),[message,setMessage]=useState(''),[error,setError]=useState('')
 async function load(){try{const [t,g,a]=await Promise.all([axios.get(`${BASE}/teachers`),axios.get(`${BASE}/teaching-assignments/groups`),axios.get(`${BASE}/teaching-assignments`)]);setTeachers(t.data);setGroups(g.data);setAssignments(a.data)}catch{setError('Could not load faculty or assignments.')}}
 useEffect(()=>{load()},[])
 const group=groups.find(g=>String(g.group_id)===String(groupId))
 async function addTeacher(e){e.preventDefault();setMessage('');setError('');if(!name.trim()){setError('Teacher name is required.');return}try{await axios.post(`${BASE}/teachers`,{teacher_name:name.trim(),max_periods_per_day:Number(max)});setMessage(`${name.trim()} added.`);setName('');setMax(6);await load()}catch(err){setError(err.response?.data?.detail||'Could not add teacher.')}}
 async function addAssignment(e){e.preventDefault();setMessage('');setError('');if(!teacherId||!definitionId||!divisionIds.length){setError('Select teacher, subject, and at least one division.');return}try{const r=await axios.post(`${BASE}/teaching-assignments`,{teacher_id:Number(teacherId),definition_id:Number(definitionId),division_ids:divisionIds.map(Number)});setMessage(r.data.message);setDivisionIds([]);await load()}catch(err){setError(err.response?.data?.detail||'Could not save assignment.')}}
 function toggleDivision(id){setDivisionIds(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 async function remove(id){try{await axios.delete(`${BASE}/teaching-assignments/${id}`);await load()}catch(err){setError(err.response?.data?.detail||'Could not delete assignment.')}}
 return <div style={page}><section style={hero}><div style={eyebrow}>STEP 3 · FACULTY & ASSIGNMENTS</div><h1 style={title}>Faculty & Assignments</h1><p style={sub}>Add each teacher once with their daily maximum. Then assign that global teacher to subjects and specific divisions.</p></section>
 <section style={card}><h2 style={h2}>1. Add faculty</h2><form onSubmit={addTeacher} style={grid}><Field label="Teacher name"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Prof. Sharma" style={input}/></Field><Field label="Maximum teaching periods / day"><input type="number" min="1" max="8" value={max} onChange={e=>setMax(e.target.value)} style={input}/></Field><button style={button}>Add Teacher</button></form><div style={teacherList}>{teachers.map(t=><div key={t.teacher_id} style={teacherCard}><b>{t.teacher_name}</b><span>{t.max_periods_per_day} max periods/day</span></div>)}</div></section>
 <section style={card}><h2 style={h2}>2. Add teaching assignment</h2><div style={grid2}><Field label="Teacher"><select value={teacherId} onChange={e=>setTeacherId(e.target.value)} style={input}><option value="">Select teacher</option>{teachers.map(t=><option key={t.teacher_id} value={t.teacher_id}>{t.teacher_name} · max {t.max_periods_per_day}/day</option>)}</select></Field><Field label="Department & year"><select value={groupId} onChange={e=>{setGroupId(e.target.value);setDefinitionId('');setDivisionIds([])}} style={input}><option value="">Select department/year</option>{groups.map(g=><option key={g.group_id} value={g.group_id}>{g.department} · {yearLabel(g.year_of_study)}</option>)}</select></Field></div>{group&&<><div style={labelStyle}>DIVISIONS</div><div style={checkRow}>{group.divisions.map(d=><label key={d.division_id} style={check}><input type="checkbox" checked={divisionIds.includes(d.division_id)} onChange={()=>toggleDivision(d.division_id)}/>{d.division_name}</label>)}</div><Field label="Subject"><select value={definitionId} onChange={e=>setDefinitionId(e.target.value)} style={input}><option value="">Select subject</option>{group.subjects.map(s=><option key={s.definition_id} value={s.definition_id}>{s.subject_name} · {s.subject_type} · {s.periods_per_week}/week</option>)}</select></Field><button onClick={addAssignment} style={button}>Add Assignment</button></>}</section>
 {message&&<div style={success}>{message}</div>}{error&&<div style={errorBox}>{error}</div>}
 <section style={card}><h2 style={h2}>Current assignments</h2>{assignments.length===0?<p style={muted}>No assignments yet.</p>:<div style={{display:'grid',gap:8}}>{assignments.map(a=><div key={a.assignment_id} style={assignment}><div><b>{a.teacher_name}</b><span style={muted}> → {a.subject_name} ({a.subject_type})</span></div><div style={muted}>{a.department} · {yearLabel(a.year_of_study)} · Division {a.division_name}</div><button onClick={()=>remove(a.assignment_id)} style={deleteBtn}>Remove</button></div>)}</div>}</section></div>
}
function Field({label,children}){return <label style={{display:'grid',gap:7,marginTop:14}}><span style={labelStyle}>{label}</span>{children}</label>}
const page={padding:'34px 38px',maxWidth:1100,margin:'0 auto'};const hero={padding:'28px 30px',borderRadius:18,background:'linear-gradient(135deg,#eef5ff,#f7f4ff)',border:'1px solid #dbe5f5',marginBottom:20};const eyebrow={fontSize:11,fontWeight:800,letterSpacing:'.12em',color:'#4f46e5'};const title={fontSize:32,margin:'8px 0 6px',color:'#172554'};const sub={margin:0,color:'#64748b',fontSize:15,lineHeight:1.6};const card={background:'#fff',border:'1px solid #e2e8f0',borderRadius:16,padding:26,marginBottom:20,boxShadow:'0 5px 20px rgba(15,23,42,.04)'};const h2={fontSize:19,color:'#172554',margin:'0 0 14px'};const grid={display:'grid',gridTemplateColumns:'2fr 1fr auto',gap:14,alignItems:'end'};const grid2={display:'grid',gridTemplateColumns:'1fr 1fr',gap:14};const input={width:'100%',boxSizing:'border-box',padding:'11px 12px',border:'1px solid #cbd5e1',borderRadius:9,fontSize:14,background:'#fff'};const button={padding:'11px 17px',border:0,borderRadius:9,background:'linear-gradient(90deg,#2563eb,#6d28d9)',color:'#fff',fontWeight:800,cursor:'pointer'};const labelStyle={fontSize:11,fontWeight:800,letterSpacing:'.08em',color:'#64748b',display:'block',marginTop:15};const teacherList={display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,marginTop:20};const teacherCard={padding:11,border:'1px solid #e2e8f0',borderRadius:9,display:'flex',justifyContent:'space-between',gap:10,fontSize:13};const checkRow={display:'flex',gap:10,margin:'9px 0 8px'};const check={padding:'8px 12px',background:'#f8fafc',border:'1px solid #e2e8f0',borderRadius:8,fontSize:13};const assignment={display:'grid',gridTemplateColumns:'1.4fr 1.4fr auto',gap:10,alignItems:'center',padding:13,border:'1px solid #e2e8f0',borderRadius:10};const deleteBtn={border:0,background:'#fee2e2',color:'#b91c1c',padding:'7px 10px',borderRadius:7,cursor:'pointer'};const muted={color:'#64748b',fontSize:12};const success={padding:12,borderRadius:9,background:'#ecfdf5',color:'#047857',marginBottom:16};const errorBox={padding:12,borderRadius:9,background:'#fef2f2',color:'#b91c1c',marginBottom:16}
